local keymap = vim.keymap

keymap.set('i', 'df', '<esc>')
keymap.set('i', 'df', '<esc>')
keymap.set('i', 'df', '<esc>')
keymap.set('i', 'df', '<esc>')
keymap.set('t', 'df', '<c-\\><c-n>')
keymap.set('t', 'df', '<c-\\><c-n>')
keymap.set('t', 'df', '<c-\\><c-n>')
keymap.set('t', 'df', '<c-\\><c-n>')
keymap.set('t', '<esc>', '<c-\\><c-n>')
keymap.set('t', '<a-m>', '<c-\\><c-n>')
keymap.set('c', '<a-m>', '<esc><esc>')
keymap.set('v', 'm', '<esc>')

keymap.set('n', '<a-y>', '"+y')
keymap.set('v', '<a-y>', '"+y')
keymap.set('n', '<a-p>', '"+p')
keymap.set('n', '<a-s-p>', '"+p')
keymap.set('v', '<a-p>', '"+p')
keymap.set('v', '<a-s-p>', '"+p')

keymap.set({'n', 'i'}, '<rightmouse>', '<leftmouse>')
keymap.set({'n', 'i'}, '<rightrelease>', '<nop>')

keymap.set('n', '<leader>f.', '<cmd>:if (&ft == "vim" || &ft == "lua") | source %:p | endif<cr>')

keymap.set('n', 'c.', '<cmd>:try|cd %:h|catch|endtry<cr>', {silent = true})
keymap.set('n', 'cu', '<cmd>:try|cd ..|catch|endtry<cr>', {silent = true})
keymap.set('n', 'c-', '<cmd>:try|cd -|catch|endtry<cr>', {silent = true})

keymap.set('n', 'q', '<nop>')
keymap.set('n', 'q', 'q')

keymap.set('n', 'U', '<c-r>')

keymap.set('n', '<c-s>', '5<c-e>')
keymap.set('n', '<c-a>', '5<c-y>')
keymap.set('n', '<c-d>', '<c-u>')
keymap.set('n', '<c-f>', '<c-d>')
keymap.set('n', '<c-u>', '<c-b>')
keymap.set('n', '<c-b>', '<c-f>')

keymap.set('n', '<leader>ba', '<c-w>s')
keymap.set('n', '<leader>bb', '<cmd>:new<cr>')

keymap.set('n', '<leader>bc', '<c-w>v')
keymap.set('n', '<leader>bd', '<cmd>:vnew<cr>')

keymap.set('n', '<leader>be', '<c-w>s<c-w>t')
keymap.set('n', '<leader>bf', '<cmd>:tabnew<cr>')

keymap.set('n', '<leader>w', '<c-w>k')
keymap.set('v', '<leader>w', '<c-w>k')
keymap.set('n', '<leader>s', '<c-w>j')
keymap.set('v', '<leader>s', '<c-w>j')
keymap.set('n', '<leader>a', '<c-w>h')
keymap.set('v', '<leader>a', '<c-w>h')
keymap.set('n', '<leader>d', '<c-w>l')
keymap.set('v', '<leader>d', '<c-w>l')
keymap.set('n', '<cr>', '<cmd>:tabnext<cr>')
keymap.set('n', '<s-cr>', '<cmd>:tabprevious<cr>')


keymap.set({ 'n', 'v', }, '<C-j>', '5j')
keymap.set({ 'n', 'v', }, '<C-k>', '5k')
keymap.set({ 'n', 'v', 't', 'c', 'i' }, '<A-k>', '<UP>')
keymap.set({ 'n', 'v', 't', 'c', 'i' }, '<A-j>', '<DOWN>')
keymap.set({ 't', 'c', 'i' }, '<C-k>', '<UP><UP><UP><UP><UP>')
keymap.set({ 't', 'c', 'i' }, '<C-j>', '<DOWN><DOWN><DOWN><DOWN><DOWN>')
keymap.set({ 't', 'c', 'i' }, '<A-i>', '<HOME>')
keymap.set({ 't', 'c', 'i' }, '<A-S-i>', '<HOME>')
keymap.set({ 't', 'c', 'i' }, '<A-o>', '<END>')
keymap.set({ 't', 'c', 'i' }, '<A-S-o>', '<END>')
keymap.set({ 't', 'c', 'i' }, '<A-l>', '<RIGHT>')
keymap.set({ 't', 'c', 'i' }, '<A-h>', '<LEFT>')
keymap.set({ 't', 'c', 'i' }, '<A-S-l>', '<RIGHT><RIGHT><RIGHT><RIGHT><RIGHT>')
keymap.set({ 't', 'c', 'i' }, '<A-S-h>', '<LEFT><LEFT><LEFT><LEFT><LEFT>')
keymap.set({ 'v', }, '<C-l>', 'L')
keymap.set({ 'v', }, '<C-h>', 'H')
keymap.set({ 'v', }, '<C-g>', 'G')
keymap.set({ 'v', }, '<C-m>', 'M')
keymap.set({ 'n', 'v', }, '<MiddleMouse>', '<Nop>')
keymap.set({ 'n', 'v', }, '<leader>1', '1gt')
keymap.set({ 'n', 'v', }, '<leader>2', '2gt')
keymap.set({ 'n', 'v', }, '<leader>3', '3gt')
keymap.set({ 'n', 'v', }, '<leader>4', '4gt')
keymap.set({ 'n', 'v', }, '<leader>5', '5gt')
keymap.set({ 'n', 'v', }, '<leader>6', '6gt')
keymap.set({ 'n', 'v', }, '<leader>7', '7gt')
keymap.set({ 'n', 'v', }, '<leader>8', '8gt')
keymap.set({ 'n', 'v', }, '<leader>9', '9gt')
keymap.set({ 'n', 'v', }, '<leader>0', '<cmd>:tablast<cr>')
keymap.set({ 'n', 'v', }, '<c-s-h>', '<cmd>:try <bar> tabmove - <bar> catch <bar> endtry<cr>')
keymap.set({ 'n', 'v', }, '<c-s-l>', '<cmd>:try <bar> tabmove + <bar> catch <bar> endtry<cr>')
keymap.set({ 'n', 'v', }, '<c-s-k>', 'gT')
keymap.set({ 'n', 'v', }, '<c-s-j>', 'gt')

keymap.set({ 'c', 'i' }, '<a-w>', '<c-r>=g:word<cr>')
keymap.set({ 'c', 'i' }, '<a-v>', '<c-r>"')
keymap.set({ 't',     }, '<a-v>', '<c-\\><c-n>pi')
keymap.set({ 'c', 'i' }, '<a-=>', '<c-r>+')
keymap.set({ 't',     }, '<a-=>', '<c-\\><c-n>"+pi')
keymap.set({ 'n', 'v' }, '<a-z>', '"zy')
keymap.set({ 'c', 'i' }, '<a-z>', '<c-r>z')
keymap.set({ 't',     }, '<a-z>', '<c-\\><c-n>"zpi')
